### ISSUE TITLE
安装启动后无法获取API数据

### ISSUE THREAD

**Issue by dodou123** [ddqre12345/vue-music#11]
可能是我太菜，还是API那边的端口改了，不知道怎么修改才能获取到API的数据，现在启动后就是不停的转。。。

**Comment by dodou123** [comment]
不知道大佬能否留一个联系方式，QQ或者微信，最近需要用vue+vux做项目，脑子都做炸了。

**Comment by ddqre12345** [comment]
原来的后端服务在我的服务器上，现在已经停了，API这块你可以根据相关文档自己在本地或者服务器上搭建一个，还有就是我这个接口当时为了识别在对应api前加了前缀，方便识别

**Comment by webliyuangit** [comment]
504 gateway time-out   网页请求不到，是什么问题啊

**Comment by ddqre12345** [comment]
@webliyuangit 先自行搭建后端服务
