### ISSUE TITLE
message

### ISSUE THREAD

**Issue by jackwms** [ddqre12345/vue-music#13]
get a code404

**Comment by ddqre12345** [comment]
这个issues我关闭了，希望下次出现问题的时候能详细描述下场景，将问题截图

**Comment by Allianzcortex** [comment]
@ddqre12345 抱歉就不开一个新 issue 了(:  我在查看网络运行状态时发现请求是向 127.0.0.1 本地发送的，但似乎并没有找到类似 mock.js/vue-test-utils 这样的模拟 API ？所以很好奇这个项目最终的数据来源是在哪里？

![image](https://user-images.githubusercontent.com/7290780/62619570-774ff700-b8ed-11e9-8dee-c04b371ef373.png)

**Comment by ddqre12345** [comment]
> @ddqre12345 抱歉就不开一个新 issue 了(: 我在查看网络运行状态时发现请求是向 127.0.0.1 本地发送的，但似乎并没有找到类似 mock.js/vue-test-utils 这样的模拟 API ？所以很好奇这个项目最终的数据来源是在哪里？
> 
> ![image](https://user-images.githubusercontent.com/7290780/62619570-774ff700-b8ed-11e9-8dee-c04b371ef373.png)

这个之前有反向代理到远程后端服务，不过现在到期了，应该已经被回收，需要到话，你可以按照https://github.com/Binaryify/NeteaseCloudMusicApi 这里的教程搭建数据服务而不是mock
