### ISSUE TITLE
我克隆并安装了。运行是报错

### ISSUE THREAD

**Issue by DestinyHunter** [ddqre12345/vue-music#3]
ERROR  Failed to compile with 9 errors                                                                                                                                               9:54:20 AM

These dependencies were not found:

* vux/src/components/Tab in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/find/find.vue, ./~/babel-loader/lib!./~/vux-l
oader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/search/search.vue and 2 others
* vux/src/components/Swiper in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/find/find.vue, ./~/babel-loader/lib!./~/vu
x-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/search/search.vue and 2 others

To install them, you can run: npm install --save vux/src/components/Tab vux/src/components/Swiper

This relative module was not found:

* ../components/header/header.vue in ./~/babel-loader/lib!./~/vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/index.vue
> Listening at http://localhost:8022

**Comment by ddqre12345** [comment]
你这个问题，我重新下载安装后没有复现，建议你可以使用cnpm install命令安装，但是先前的包发现了一个eslint下编译错误的bug，已修复，建议重新下载新包尝试，还有就是你这个问题可能是vux-loader等未全局安装引起的，你可以尝试下npm install vux-loader -g，希望能解决你的问题

**Comment by magicknight** [comment]
If you are running this on Linux, try to change the upper character to lower character, for example, 
/Tab -> /tab

**Comment by ddqre12345** [comment]
> ERROR Failed to compile with 9 errors 9:54:20 AM
> 
> These dependencies were not found:
> 
> * vux/src/components/Tab in .//babel-loader/lib!.//vux-loader/src/script-loader.js!.//vue-loader/lib/selector.js?type=script&index=0!./src/views/find/find.vue, .//babel-loader/lib!.//vux-l
>   oader/src/script-loader.js!.//vue-loader/lib/selector.js?type=script&index=0!./src/views/search/search.vue and 2 others
> * vux/src/components/Swiper in .//babel-loader/lib!.//vux-loader/src/script-loader.js!.//vue-loader/lib/selector.js?type=script&index=0!./src/views/find/find.vue, .//babel-loader/lib!.//vu
>   x-loader/src/script-loader.js!.//vue-loader/lib/selector.js?type=script&index=0!./src/views/search/search.vue and 2 others
> 
> To install them, you can run: npm install --save vux/src/components/Tab vux/src/components/Swiper
> 
> This relative module was not found:
> 
> * ../components/header/header.vue in .//babel-loader/lib!.//vux-loader/src/script-loader.js!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/index.vue
> 
> > Listening at http://localhost:8022

非常抱歉，到现在才给你回复，这是vux组件导入路径的问题，当然也包括header组件大写的问题，现在已经修复了，因为这部分只在linux中出现，所以之前没有注意到

**Comment by ddqre12345** [comment]
> If you are running this on Linux, try to change the upper character to lower character, for example,
> /Tab -> /tab

是的，在linux下确实有这样的情况，引入路径的问题

**Comment by magicknight** [comment]
> > If you are running this on Linux, try to change the upper character to lower character, for example,
> > /Tab -> /tab
> 
> 是的，在linux下确实有这样的情况，引入路径的问题

Two years late man...
