### ISSUE TITLE
关于差异化的建议

### ISSUE THREAD

**Issue by eromoe** [ddqre12345/vue-music#7]
因为原版云音乐的管理操作实在是很别扭，缺少一些本地播放器常用的功能， 我觉得一些用户痛点可能是在修改歌单上，不知道能不能针对这方面进行一些优化？

比如：
1. 保存歌单时直接保存为自己的歌单（原版需要保存，然后清空播放列表，找到那个歌单全部播放，保存列表，然后才能改）
2. 合并歌单  (没这个功能， 需要清空播放列表，找到想合并的歌单点全部播放，再找另一个，最后保存)
3. 设置封面图 （没这个功能）
4. 将选中歌曲（或者歌单/播放列表）添加到  类似购物车（音乐车） 的篮子里，可以将篮子里的歌创建为一个歌单 （至少在windows版上，我对列表点击 添加到播放列表，会导致覆盖当前列表。）
5. 多级文件夹  (通过google driver 之类的保存数据 结构？)

**Comment by ddqre12345** [comment]
首先，非常感谢你提供的建议，最近由于工作的原因，这个项目暂时没有继续推进，节后应该会有一定的优化输出，你提供的建议我这边会认真评估，不过因为接口来源为第三方网易云的，所以部分功能可能即使实现也只能做到本地存储，最后，很感谢你对本项目的关注，这个项目会继续推进下去，至于以后是模仿还是基于网易云音乐自定义界面，哈哈，一切皆有可能，希望你今后有时间能稍微关注下，提供更多的建议来完善它
