### ISSUE TITLE
1140019140@qq.com

### ISSUE THREAD

**Issue by vuelmc** [ddqre12345/vue-music#8]
您好，我用你的源码一直报[HPM] Error occurred while trying to proxy request /api/top/list?idx=1 from loca
lhost:8080 to http://118.89.226.181:3000 (ECONNREFUSED) (https://nodejs.org/api/
errors.html#errors_common_system_errors)这个错误
一直在排查dev: {
    env: require('./dev.env'),
    port: 8080,
    autoOpenBrowser: true,
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {
      '/api': {
        target: 'http://118.89.226.181:3000',
        changeOrigin: true,
      }
    },
如果您有解决方案请发到我邮箱谢谢

**Comment by ddqre12345** [comment]
http://118.89.226.181:3000这个接口目前已经不提供服务了，你可以自己搭建后端服务，本地请求，或者挂服务器上

**Comment by vuelmc** [comment]
请大神指点

**Comment by ddqre12345** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi 这是接口来源，你可以根据这个来部署本地的node服务

**Comment by tzzhmm** [comment]
我遇到页面报 504  
spread.js:25 GET http://localhost:8080/api/personalized 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
recommend.vue?0c3c:70 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/personalized/privatecontent 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
recommend.vue?0c3c:78 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/personalized/mv 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
recommend.vue?0c3c:86 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/personalized/djprogram 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
recommend.vue?0c3c:102 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/personalized/newsong 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
recommend.vue?0c3c:94 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/top/list?idx=3 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
ranking.vue?1f4d:74 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/top/list?idx=0 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
ranking.vue?1f4d:84 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/top/playlist?order=new&limit=20&offset=0 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
playLists.vue?5fae:34 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/top/list?idx=2 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
ranking.vue?1f4d:94 Error: Request failed with status code 504(…)
spread.js:25 GET http://localhost:8080/api/top/list?idx=1 504 (Gateway Timeout)(anonymous function) @ spread.js:25e.exports @ spread.js:25e.exports @ spread.js:25
ranking.vue?1f4d:104 Error: Request failed with status code 504(…)
