### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by wanglixiong** [ddqre12345/vue-music#9]
npm install 
npm run dev
报错 发现是vux/componets/Tab vux/componets/Swiper
这个应该在import 的时候小写 但是大写了
还有Header/Header.vue Header/Header.styl这个 也因为引用是小写 实际文件名大写
还有Onlinetrac 也是大小写 导致引用错误

**Comment by ddqre12345** [comment]
确实,中间修改过，不过git设置为了忽略大小写所以没注意，但是linux系统不忽略大小写，所以导致了这个问题，已经修复
